spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crud_spring
    username: postgres
    password: senha
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
